name: ISC-Football
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core System & Python
  - python=3.12
  - pip
  - pyyaml
  - openblas
  
  # Heavy Data Science & Vision (Better handled by Conda for OS binaries)
  - numpy
  - pandas
  - matplotlib-base
  - seaborn
  - scikit-learn
  - scipy
  - opencv
  - h5py
  
  # PyTorch (Explicitly fetching from the official pytorch channels for Linux/CUDA support)
  - pytorch
  - torchvision
  - torchaudio